### ISSUE TITLE
Make the module not specific to GCP

### ISSUE THREAD

**Issue by fedorov** [deepakri201/mpReview#1]
Right now, it is expected that DICOMweb interface is always provided by Google Cloud Platform, which means there will always be expectation to have project-dataset-dicom store hierarchy. Instead, we should somehow make the module agnostic to the DICOMweb provider. In the general case, there will be a DICOMweb URL endpoint and it should be possible to use it in the module.

**Comment by deepakri201** [comment]
This has been completed. The module now includes an option to use a server URL other than from Google Cloud Platform.
